<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
        ['name' => 'Afghan afghani','sign' => '؋','symbol' => 'AFN'],
        ['name' => 'Euro', 'sign' => '€','symbol' => 'EUR'],
        ['name' => 'Albanian lek', 'sign' => 'Lek','symbol' => 'ALL'],
        ['name' => 'Algerian dinar', 'sign' => 'دج','symbol' => 'DZD'],
        ['name' => 'United States dollar', 'sign' => '$','symbol' => 'USD'],
        ['name' => 'Angolan kwanza', 'sign' => 'Kz','symbol' => 'AOA'],
        ['name' => 'Eastern Caribbean dollar', 'sign' => '$','symbol' => 'XCD'],
        ['name' => 'Antarctic dollar', 'sign' => '$','symbol' => 'AAD'],
        ['name' => 'Argentine peso', 'sign' => '$','symbol' => 'ARS'],
        ['name' => 'Armenian dram', 'sign' => '֏','symbol' => 'AMD'],
        ['name' => 'Russian ruble', 'sign' => 'ƒ','symbol' => 'AWG'],
        ['name' => 'Australian dollar', 'sign' => '$','symbol' => 'AUD'],
        ['name' => 'Azerbaijani manat', 'sign' => 'm','symbol' => 'AZN'],
        ['name' => 'Bahamian dollar', 'sign' => 'B$','symbol' => 'BSD'],
        ['name' => 'Bahraini dinar', 'sign' => '.د.ب','symbol' => 'BHD'],
        ['name' => 'Barbadian dollar', 'sign' => 'Bds$','symbol' => 'BBD'],
        ['name' => 'Belarusian ruble', 'sign' => 'Br','symbol' => 'BYN'],
        ['name' => 'Belize dollar', 'sign' => '$','symbol' => 'BZD'],
        ['name' => 'West African CFA franc', 'sign' => 'CFA','symbol' => 'XOF'],
        ['name' => 'Bermudian dollar', 'sign' => '$','symbol' => 'BMD'],
        ['name' => 'Bhutanese ngultrum', 'sign' => 'Nu.','symbol' => 'BTN'],
        ['name' => 'Bolivian boliviano', 'sign' => 'Bs.','symbol' => 'BOB'],
        ['name' => 'Bosnia and Herzegovina convertible mark', 'sign' => 'KM','symbol' => 'BAM'],
        ['name' => 'Botswana pula', 'sign' => 'P','symbol' => 'BWP'],
        ['name' => 'Norwegian krone', 'sign' => 'kr','symbol' => 'NOK'],
        ['name' => 'Brazilian real', 'sign' => 'R$','symbol' => 'BRL'],
        ['name' => 'Brunei dollar', 'sign' => 'B$','symbol' => 'BND'],
        ['name' => 'Bulgarian lev', 'sign' => 'Лв.','symbol' => 'BGN'],
        ['name' => 'Burundian franc	', 'sign' => 'FBu','symbol' => 'BIF'],
        ['name' => 'Cambodian riel', 'sign' => 'KHR','symbol' => 'KHR'],
        ['name' => 'Central African CFA franc', 'sign' => 'FCFA','symbol' => 'XAF'],
        ['name' => 'Canadian dollar', 'sign' => '$','symbol' => 'CAD'],
        ['name' => 'Cape Verdean escudo	', 'sign' => '$','symbol' => 'CVE'],
        ['name' => 'Cayman Islands dollar', 'sign' => '$','symbol' => 'KYD'],
        ['name' => 'Chilean peso', 'sign' => '$','symbol' => 'CLP'],
        ['name' => 'Chinese yuan', 'sign' => '¥','symbol' => 'CNY'],
        ['name' => 'Colombian peso', 'sign' => '$','symbol' => 'COP'],
        ['name' => 'Comorian franc', 'sign' => 'CF','symbol' => 'KMF'],
        ['name' => 'Congolese franc', 'sign' => 'FC','symbol' => 'XAF'],
        ['name' => 'Cook Islands dollar', 'sign' => '$','symbol' => 'NZD'],
        ['name' => 'Colones', 'sign' => '₡','symbol' => 'CRC'],
        ['name' => 'Croatian kuna', 'sign' => 'kn','symbol' => 'HRK'],
        ['name' => 'Cuban peso', 'sign' => '$','symbol' => 'CUP'],
        ['name' => 'Czech koruna', 'sign' => 'Kč','symbol' => 'CZK'],
        ['name' => 'Danish krone', 'sign' => 'Kr.','symbol' => 'DKK'],
        ['name' => 'Djiboutian franc', 'sign' => 'Fdj','symbol' => 'DJF'],
        ['name' => 'Dominican peso', 'sign' => '$','symbol' => 'DOP'],
        ['name' => 'Egyptian pound', 'sign' => 'ج.م','symbol' => 'EGP'],
        ['name' => 'Eritrean nakfa', 'sign' => 'Nfk','symbol' => 'ERN'],
        ['name' => 'Ethiopian birr', 'sign' => 'Nkf','symbol' => 'ETB'],
        ['name' => 'Falkland Islands pound', 'sign' => '£','symbol' => 'FKP'],
        ['name' => 'Fijian dollar', 'sign' => 'FJ$','symbol' => 'FJD'],
        ['name' => 'CFP franc', 'sign' => '₣','symbol' => 'XPF'],
        ['name' => 'Gambian dalasi', 'sign' => 'D','symbol' => 'GMD'],
        ['name' => 'Georgian lari', 'sign' => 'ლ','symbol' => 'GEL'],
        ['name' => 'Ghanaian cedi', 'sign' => 'GH₵','symbol' => 'GHS'],
        ['name' => 'Gibraltar pound', 'sign' => '£','symbol' => 'GIP'],
        ['name' => 'Guatemalan quetzal', 'sign' => 'Q','symbol' => 'GTQ'],
        ['name' => 'British pound', 'sign' => '£','symbol' => 'GBP'],
        ['name' => 'Guinean franc', 'sign' => 'FG','symbol' => 'GNF'],
        ['name' => 'Guyanese dollar', 'sign' => '$','symbol' => 'GYD'],
        ['name' => 'Haitian gourde	haitian-gourde	G	','symbol' => 'HTG'],
        ['name' => 'Honduran lempira', 'sign' => 'L','symbol' => 'HNL'],
        ['name' => 'Hong Kong dollar', 'sign' => '$','symbol' => 'HKD'],
        ['name' => 'Hungarian forint', 'sign' => 'Ft','symbol' => 'HUF'],
        ['name' => 'Icelandic króna', 'sign' => 'kr','symbol' => 'ISK'],
        ['name' => 'Indian rupee', 'sign' => '₹','symbol' => 'INR'],
        ['name' => 'Indonesian rupiah', 'sign' => 'Rp','symbol' => 'IDR'],
        ['name' => 'Iranian rial', 'sign' => '﷼','symbol' => 'IRR'],
        ['name' => 'Iraqi dinar', 'sign' => 'د.ع','symbol' => 'IQD'],
        ['name' => 'Israeli new shekel', 'sign' => '₪','symbol' => 'ILS'],
        ['name' => 'Jamaican dollar', 'sign' => 'J$','symbol' => 'JMD'],
        ['name' => 'Japanese yen', 'sign' => '¥','symbol' => 'JPY'],
        ['name' => 'Jordanian dinar', 'sign' => 'ا.د','symbol' => 'JOD'],
        ['name' => 'Kazakhstani tenge', 'sign' => 'лв','symbol' => 'KZT'],
        ['name' => 'Kenyan shilling', 'sign' => 'KSh','symbol' => 'KES'],
        ['name' => 'North Korean won', 'sign' => '₩','symbol' => 'KPW'],
        ['name' => 'South Korean won', 'sign' => '₩','symbol' => 'KRW'],
        ['name' => 'Kuwaiti dinar', 'sign' => 'ك.د','symbol' => 'KWD'],
        ['name' => 'Kyrgyzstani som', 'sign' => 'лв','symbol' => 'KGS'],
        ['name' => 'Lao kip', 'sign' => '₭','symbol' => 'LAK'],
        ['name' => 'Lebanese pound', 'sign' => '£','symbol' => 'LBP'],
        ['name' => 'Lesotho loti', 'sign' => 'L','symbol' => 'LSL'],
        ['name' => 'Liberian dollar', 'sign' => '$','symbol' => 'LRD'],
        ['name' => 'Libyan dinar', 'sign' => 'د.ل','symbol' => 'LYD'],
        ['name' => 'Swiss franc', 'sign' => 'CHf','symbol' => 'CHF'],
        ['name' => 'Macanese pataca', 'sign' => '$','symbol' => 'MOP'],
        ['name' => 'Macedonian denar', 'sign' => 'ден','symbol' => 'MKD'],
        ['name' => 'Malagasy ariary', 'sign' => 'Ar','symbol' => 'MGA'],
        ['name' => 'Malawian kwacha', 'sign' => 'MK','symbol' => 'MWK'],
        ['name' => 'Malaysian ringgit', 'sign' => 'RM','symbol' => 'MYR'],
        ['name' => 'Maldivian rufiyaa', 'sign' => 'Rf','symbol' => 'MVR'],
        ['name' => 'Mauritanian ouguiya', 'sign' => 'MRU','symbol' => 'MRO'],
        ['name' => 'Mauritian rupee', 'sign' => '₨','symbol' => 'MUR'],
        ['name' => 'Mexican peso', 'sign' => '$','symbol' => 'MXN'],
        ['name' => 'Moldovan leu', 'sign' => 'L','symbol' => 'MDL'],
        ['name' => 'Mongolian tögrög', 'sign' => '₮','symbol' => 'MNT'],
        ['name' => 'Moroccan dirham', 'sign' => 'DH','symbol' => 'MAD'],
        ['name' => 'Mozambican metical', 'sign' => 'MT','symbol' => 'MZN'],
        ['name' => 'Burmese kyat', 'sign' => 'K','symbol' => 'MMK'],
        ['name' => 'Namibian dollar', 'sign' => '$','symbol' => 'NAD'],
        ['name' => 'Nepalese rupee', 'sign' => '₨','symbol' => 'NPR'],
        ['name' => 'New Zealand dollar', 'sign' => '$','symbol' => 'NZD'],
        ['name' => 'Nicaraguan córdoba', 'sign' => 'C$','symbol' => 'NIO'],
        ['name' => 'Nigerian naira', 'sign' => '₦','symbol' => 'NGN'],
        ['name' => 'Omani rial', 'sign' => '.ع.ر','symbol' => 'OMR'],
        ['name' => 'Pakistani rupee', 'sign' => '₨','symbol' => 'PKR'],
        ['name' => 'Panamanian balboa', 'sign' => 'B/.','symbol' => 'PAB'],
        ['name' => 'Papua New Guinean kina', 'sign' => 'K','symbol' => 'PGK'],
        ['name' => 'Paraguayan guaraní', 'sign' => '₲','symbol' => 'PYG'],
        ['name' => 'Peruvian sol', 'sign' => 'S/.','symbol' => 'PEN'],
        ['name' => 'Philippine peso', 'sign' => '₱','symbol' => 'PHP'],
        ['name' => 'Polish złoty', 'sign' => 'zł','symbol' => 'PLN'],
        ['name' => 'Qatari riyal', 'sign' => 'ق.ر','symbol' => 'QAR'],
        ['name' => 'Rwandan franc', 'sign' => 'FRw','symbol' => 'RWF'],
        ['name' => 'Saint Helena pound', 'sign' => '£','symbol' => 'SHP'],
        ['name' => 'Samoa', 'sign' => 'SAT','symbol' => 'WST'],
        ['name' => 'São Tomé and Príncipe dobra', 'sign' => 'Db','symbol' => 'STD'],
        ['name' => 'Saudi riyal', 'sign' => '﷼','symbol' => 'SAR'],
        ['name' => 'Serbian dinar', 'sign' => 'din','symbol' => 'RSD'],
        ['name' => 'Seychellois rupee', 'sign' => 'SRe','symbol' => 'SCR'],
        ['name' => 'Sierra Leonean leone', 'sign' => 'Le','symbol' => 'SLL'],
        ['name' => 'Singapore dollar', 'sign' => '$','symbol' => 'SGD'],
        ['name' => 'Solomon Islands dollar', 'sign' => 'Si$','symbol' => 'SBD'],
        ['name' => 'Somali shilling', 'sign' => 'Sh.so.','symbol' => 'SOS'],
        ['name' => 'South African rand', 'sign' => 'R','symbol' => 'ZAR'],
        ['name' => 'South Sudanese pound', 'sign' => '£','symbol' => 'SSP'],
        ['name' => 'Sri Lankan rupee', 'sign' => 'Rs','symbol' => 'LKR'],
        ['name' => 'Sudanese pound', 'sign' => '.س.ج','symbol' => 'SDG'],
        ['name' => 'Surinamese dollar', 'sign' => '$','symbol' => 'SRD'],
        ['name' => 'Swazi lilangeni', 'sign' => 'E','symbol' => 'SZL'],
        ['name' => 'Swedish krona', 'sign' => 'kr','symbol' => 'SEK'],
        ['name' => 'Syrian pound', 'sign' => 'LS','symbol' => 'SYP'],
        ['name' => 'New Taiwan dollar', 'sign' => '$','symbol' => 'TWD'],
        ['name' => 'Tajikistani somoni', 'sign' => 'SM','symbol' => 'TJS'],
        ['name' => 'Tanzanian shilling', 'sign' => 'TSh','symbol' => 'TZS'],
        ['name' => 'Thai baht', 'sign' => '฿','symbol' => 'THB'],
        ['name' => 'Tongan paʻanga', 'sign' => '$','symbol' => 'TOP'],
        ['name' => 'Trinidad and Tobago dollar', 'sign' => '$','symbol' => 'TTD'],
        ['name' => 'Tunisia', 'sign' => 'ت.د','symbol' => 'TND'],
        ['name' => 'Turkish lira', 'sign' => '₺','symbol' => 'TRY'],
        ['name' => 'Turkmenistan manat', 'sign' => 'T','symbol' => 'TMT'],
        ['name' => 'Ugandan shilling', 'sign' => 'USh','symbol' => 'UGX'],
        ['name' => 'Ukrainian hryvnia', 'sign' => '₴','symbol' => 'UAH'],
        ['name' => 'United Arab Emirates dirham', 'sign' => 'إ.د','symbol' => 'AED'],
        ['name' => 'Uruguayan peso', 'sign' => '$','symbol' => 'UYU'],
        ['name' => 'Uzbekistani soʻm', 'sign' => 'лв','symbol' => 'UZS'],
        ['name' => 'Vanuatu vatu', 'sign' => 'VT','symbol' => 'VUV'],
        ['name' => 'Venezuelan bolívar soberano', 'sign' => 'Bs','symbol' => 'VEF'],
        ['name' => 'Vietnamese đồng', 'sign' => '₫','symbol' => 'VND'],
        ['name' => 'Yemeni rial', 'sign' => '﷼','symbol' => 'YER'],
        ['name' => 'Zambian kwacha', 'sign' => 'ZK','symbol' => 'ZMW'],
        ['name' => 'RTGS dollar', 'sign' => '$','symbol' => 'ZWL'],
        ['name' => 'Netherlands Antillean guilder', 'sign' => 'ƒ','symbol' => 'ANG'],
        ];


        foreach($data as $datum){
            $currency = Currency::where('name', $datum['name'])->first();

            if (!$currency) {
                $currency = new Currency();
                $currency->uid = Str::orderedUuid();
            }   

            $currency->name = $datum['name'];
            $currency->sign = $datum['sign'];
            $currency->symbol = $datum['symbol'];
            $currency->save();
        }
       
    }
}
