<?php

namespace Database\Seeders;

use App\Models\Timezone;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['zone_name' => 'Asia/Kabul','short_code' => 'AFT','gmt_offset' => 'UTC +04:30'],
            ['zone_name' => 'Europe/Tirane','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Algiers','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Pacific/Pago_Pago','short_code' => 'SST','gmt_offset' => 'UTC -11:00'],
            ['zone_name' => 'Europe/Andorra','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Luanda','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Anguilla','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Antarctica/Casey','short_code' => 'CAST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Antarctica/Davis','short_code' => 'DAVT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Antarctica/DumontDUrville','short_code' => 'DDUT','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Antarctica/Mawson','short_code' => 'MAWT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Antarctica/McMurdo','short_code' => 'NZDT','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'Antarctica/Palmer','short_code' => 'CLST','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Antarctica/Rothera','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Antarctica/Syowa','short_code' => 'SYOT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Antarctica/Troll','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Antarctica/Vostok','short_code' => 'VOST','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'America/Antigua','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Argentina/Buenos_Aires','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Catamarca','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Cordoba','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Jujuy','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/La_Rioja','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Mendoza','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Rio_Gallegos','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Salta','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/San_Juan','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/San_Luis','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Tucuman','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Argentina/Ushuaia','short_code' => 'ART','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Asia/Yerevan','short_code' => 'AMT','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'America/Aruba','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Antarctica/Macquarie','short_code' => 'AEDT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Australia/Adelaide','short_code' => 'ACDT','gmt_offset' => 'UTC +10:30'],
            ['zone_name' => 'Australia/Brisbane','short_code' => 'AEST','gmt_offset' => 'UTC +10:00'],       
            ['zone_name' => 'Australia/Broken_Hill','short_code' => 'ACDT','gmt_offset' => 'UTC +10:30'],
            ['zone_name' => 'Australia/Darwin','short_code' => 'ACST','gmt_offset' => 'UTC +09:30'],
            ['zone_name' => 'Australia/Eucla','short_code' => 'ACWST','gmt_offset' => 'UTC +08:45'],
            ['zone_name' => 'Australia/Hobart','short_code' => 'AEDT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Australia/Lindeman','short_code' => 'AEST','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Australia/Lord_Howe','short_code' => 'LHDT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Australia/Melbourne','short_code' => 'AEDT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Australia/Perth','short_code' => 'AWST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Australia/Sydney','short_code' => 'AEDT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Europe/Vienna','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Baku','short_code' => 'AZT','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'America/Nassau','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Asia/Bahrain','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Dhaka','short_code' => 'BST','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'America/Barbados','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Europe/Minsk','short_code' => 'MSK','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Brussels','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Belize','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Africa/Porto-Novo','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Atlantic/Bermuda','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Asia/Thimphu','short_code' => 'BTT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'America/La_Paz','short_code' => 'BOT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Kralendijk','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Europe/Sarajevo','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Gaborone','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'America/Araguaina','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Bahia','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Belem','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Boa_Vista','short_code' => 'AMT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Campo_Grande','short_code' => 'AMT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Cuiaba','short_code' => 'BRT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Eirunepe','short_code' => 'ACT','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Fortaleza','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Maceio','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Manaus','short_code' => 'AMT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Noronha','short_code' => 'FNT','gmt_offset' => 'UTC -02:00'],
            ['zone_name' => 'America/Porto_Velho','short_code' => 'AMT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Recife','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Rio_Branco','short_code' => 'ACT','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Santarem','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Sao_Paulo','short_code' => 'BRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Indian/Chagos','short_code' => 'IOT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Asia/Brunei	','short_code' => 'BNT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Europe/Sofia','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Ouagadougou','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Africa/Bujumbura','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Phnom_Penh','short_code' => 'ICT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Africa/Douala','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Atikokan','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Blanc-Sablon','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Cambridge_Bay','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Creston','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Dawson','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Dawson_Creek','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Edmonton','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Fort_Nelson','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Glace_Bay','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Goose_Bay','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Halifax','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Inuvik','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Iqaluit','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Moncton','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Rankin_Inlet','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Regina','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Resolute','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/St_Johns','short_code' => 'NST','gmt_offset' => 'UTC -03:30'],
            ['zone_name' => 'America/Swift_Current','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Toronto','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Vancouver','short_code' => 'PST','gmt_offset' => 'UTC -08:00'],
            ['zone_name' => 'America/Whitehorse','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Winnipeg','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Atlantic/Cape_Verde','short_code' => 'CVT','gmt_offset' => 'UTC -01:00'],
            ['zone_name' => 'America/Cayman','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Africa/Bangui','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Ndjamena','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Punta_Arenas','short_code' => 'CLT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Santiago','short_code' => 'CLST','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Pacific/Easter','short_code' => 'EASST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Asia/Shanghai','short_code' => 'CST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Urumqi','short_code' => 'URUT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Indian/Christmas','short_code' => 'CXT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Indian/Cocos','short_code' => 'CCT','gmt_offset' => 'UTC +06:30'],
            ['zone_name' => 'America/Bogota','short_code' => 'COT','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Indian/Comoro','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Brazzaville','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Kinshasa','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Lubumbashi','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Pacific/Rarotonga','short_code' => 'CKT','gmt_offset' => 'UTC -10:00'],
            ['zone_name' => 'America/Costa_Rica','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Europe/Zagreb','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Havana','short_code' => 'CST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Curacao','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Asia/Famagusta','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Nicosia','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Prague','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Abidjan','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Copenhagen','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Djibouti','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'America/Dominica','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Santo_Domingo','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Guayaquil','short_code' => 'ECT','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Pacific/Galapagos','short_code' => 'GALT','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Africa/Cairo','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'America/El_Salvador','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Africa/Malabo','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Asmara','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Tallinn','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Addis_Ababa','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Atlantic/Stanley','short_code' => 'FKT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Atlantic/Faroe','short_code' => 'WET','gmt_offset' => 'UTC'],
            ['zone_name' => 'Pacific/Fiji','short_code' => 'FJT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Europe/Helsinki','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Paris','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Cayenne','short_code' => 'GFT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Pacific/Gambier','short_code' => 'GAMT','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'Pacific/Marquesas','short_code' => 'MART','gmt_offset' => 'UTC -09:30'],
            ['zone_name' => 'Pacific/Tahiti','short_code' => 'TAHT','gmt_offset' => 'UTC -10:00'],
            ['zone_name' => 'Indian/Kerguelen','short_code' => 'TFT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Africa/Libreville','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Banjul','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Tbilisi','short_code' => 'GET','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/Berlin','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Busingen','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Accra','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Gibraltar','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Athens','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'America/Danmarkshavn','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'America/Nuuk','short_code' => 'WGT','gmt_offset' => 'UTC -02:00'],
            ['zone_name' => 'America/Scoresbysund','short_code' => 'EGT','gmt_offset' => 'UTC -01:00'],
            ['zone_name' => 'America/Thule','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Grenada','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Guadeloupe','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Pacific/Guam','short_code' => 'ChST','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'America/Guatemala','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Europe/Guernsey','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Africa/Conakry','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Africa/Bissau','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'America/Guyana','short_code' => 'GYT','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Port-au-Prince','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Europe/Vatican','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Tegucigalpa','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Asia/Hong_Kong','short_code' => 'HKT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Europe/Budapest','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Atlantic/Reykjavik','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Kolkata','short_code' => 'IST','gmt_offset' => 'UTC +05:30'],
            ['zone_name' => 'Asia/Jakarta','short_code' => 'WIB','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Jayapura','short_code' => 'WIT','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Makassar','short_code' => 'WITA','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Pontianak','short_code' => 'WIB','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Tehran','short_code' => 'IRDT','gmt_offset' => 'UTC +03:30'],
            ['zone_name' => 'Asia/Baghdad','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Dublin','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Isle_of_Man','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Jerusalem','short_code' => 'IST','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Rome','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Jamaica','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Asia/Tokyo','short_code' => 'JST','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Europe/Jersey','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Amman','short_code' => 'EET','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Almaty','short_code' => 'ALMT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Asia/Aqtau','short_code' => 'AQTT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Asia/Aqtobe','short_code' => 'AQTT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Asia/Atyrau','short_code' => 'AQTT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Asia/Oral','short_code' => 'ORAT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Asia/Qostanay','short_code' => 'QYZT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Asia/Qyzylorda','short_code' => 'MSK+2','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Africa/Nairobi','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Pacific/Kanton','short_code' => 'EST','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'Pacific/Kiritimati','short_code' => 'LINT','gmt_offset' => 'UTC +14:00'],
            ['zone_name' => 'Pacific/Tarawa','short_code' => 'GILT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Asia/Pyongyang','short_code' => 'KST','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Seoul','short_code' => 'KST','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Kuwait','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Bishkek','short_code' => 'KGT','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Asia/Vientiane','short_code' => 'ICT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Europe/Riga','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Beirut','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Maseru','short_code' => 'SAST','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Monrovia','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Africa/Tripoli','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Vaduz','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Vilnius','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Luxembourg','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Macau','short_code' => 'CST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Europe/Skopje','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Indian/Antananarivo','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Blantyre','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Kuala_Lumpur','short_code' => 'MYT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Kuching','short_code' => 'MYT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Indian/Maldives','short_code' => 'MVT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Africa/Bamako','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Malta','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Pacific/Kwajalein','short_code' => '+12','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Pacific/Majuro','short_code' => '+12','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'America/Martinique','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Africa/Nouakchott','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Indian/Mauritius','short_code' => 'MUT','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Indian/Mayotte','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'America/Bahia_Banderas','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Cancun','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Chihuahua','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Ciudad_Juarez','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Hermosillo','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Matamoros','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Mazatlan','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Merida','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Mexico_City','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Monterrey','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Ojinaga','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Tijuana','short_code' => 'PST','gmt_offset' => 'UTC -08:00'],
            ['zone_name' => 'Pacific/Chuuk','short_code' => 'CHUT','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Pacific/Kosrae','short_code' => 'KOST','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Pacific/Pohnpei','short_code' => 'PONT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Europe/Chisinau','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Monaco','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Choibalsan','short_code' => 'CHOT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Hovd','short_code' => 'HOVT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Ulaanbaatar','short_code' => 'ULAT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Europe/Podgorica','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'America/Montserrat','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Africa/Casablanca','short_code' => 'WEST','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/El_Aaiun','short_code' => 'WEST','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Maputo','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Yangon','short_code' => 'MMT','gmt_offset' => 'UTC +06:30'],
            ['zone_name' => 'Africa/Windhoek','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Pacific/Nauru','short_code' => 'NRT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Asia/Kathmandu','short_code' => 'NPT','gmt_offset' => 'UTC +05:45'],
            ['zone_name' => 'Europe/Amsterdam','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Pacific/Noumea','short_code' => 'NCT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Pacific/Auckland','short_code' => 'NZDT','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'Pacific/Chatham','short_code' => 'CHADT','gmt_offset' => 'UTC +13:45'],
            ['zone_name' => 'America/Managua','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'Africa/Niamey','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Lagos','short_code' => 'WAT','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Pacific/Niue','short_code' => 'NUT','gmt_offset' => 'UTC -11:00'],
            ['zone_name' => 'Pacific/Norfolk','short_code' => 'NFDT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Pacific/Saipan','short_code' => 'ChST','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Europe/Oslo','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Muscat','short_code' => 'GST','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Asia/Karachi','short_code' => 'PKT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Pacific/Palau','short_code' => '+09','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Gaza','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Hebron','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'America/Panama','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Pacific/Bougainville','short_code' => 'BST','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Pacific/Port_Moresby','short_code' => 'PGT','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'America/Asuncion','short_code' => 'PYST','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/Lima','short_code' => 'PET','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Asia/Manila','short_code' => 'PST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Pacific/Pitcairn','short_code' => 'PST','gmt_offset' => 'UTC -08:00'],
            ['zone_name' => 'Europe/Warsaw','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Atlantic/Azores','short_code' => 'AZOT','gmt_offset' => 'UTC -01:00'],
            ['zone_name' => 'Atlantic/Madeira','short_code' => 'WET','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Lisbon','short_code' => 'WET','gmt_offset' => 'UTC'],
            ['zone_name' => 'America/Puerto_Rico','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Asia/Qatar','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Bucharest','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Asia/Anadyr','short_code' => 'ANAT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Asia/Barnaul','short_code' => 'MSK+4','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Chita','short_code' => 'YAKT','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Irkutsk','short_code' => 'IRKT','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Kamchatka','short_code' => 'PETT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Asia/Khandyga','short_code' => 'YAKT','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Krasnoyarsk','short_code' => 'KRAT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Magadan','short_code' => 'MAGT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Asia/Novokuznetsk','short_code' => 'KRAT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Novosibirsk','short_code' => 'NOVT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Omsk','short_code' => 'OMST','gmt_offset' => 'UTC +06:00'],
            ['zone_name' => 'Asia/Sakhalin','short_code' => 'SAKT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Asia/Srednekolymsk','short_code' => 'SRET','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Asia/Tomsk','short_code' => 'MSD+3','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Ust-Nera','short_code' => 'VLAT','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Asia/Vladivostok','short_code' => 'VLAT','gmt_offset' => 'UTC +10:00'],
            ['zone_name' => 'Asia/Yakutsk','short_code' => 'VLAT','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Asia/Yekaterinburg','short_code' => 'YEKT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Europe/Astrakhan','short_code' => 'MSK+1','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/Kaliningrad','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Kirov','short_code' => 'MSK','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Moscow','short_code' => 'MSK','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Samara','short_code' => 'SAMT','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/Saratov','short_code' => 'MSD','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/Ulyanovsk','short_code' => 'MSK+1','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/Volgograd','short_code' => 'MSK','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Kigali','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Indian/Reunion','short_code' => 'RET','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'America/St_Barthelemy','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Atlantic/St_Helena','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'America/St_Kitts','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/St_Lucia','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Marigot','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/Miquelon','short_code' => 'PMDT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'America/St_Vincent','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Pacific/Apia','short_code' => 'WST','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'Europe/San_Marino','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Sao_Tome','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Riyadh','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Dakar','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Belgrade','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Indian/Mahe','short_code' => 'SCT','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Africa/Freetown','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Asia/Singapore','short_code' => 'SST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'America/Lower_Princes','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Europe/Bratislava','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Ljubljana','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Pacific/Guadalcanal','short_code' => 'SBT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'Africa/Mogadishu','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Johannesburg','short_code' => 'SAST','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Atlantic/South_Georgia','short_code' => 'GST','gmt_offset' => 'UTC -02:00'],
            ['zone_name' => 'Africa/Juba','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Ceuta','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Atlantic/Canary','short_code' => 'WET','gmt_offset' => 'UTC'],
            ['zone_name' => 'Europe/Madrid','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Colombo','short_code' => 'IST','gmt_offset' => 'UTC +05:30'],
            ['zone_name' => 'Africa/Khartoum','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'America/Paramaribo','short_code' => 'SRT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Arctic/Longyearbyen','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Africa/Mbabane','short_code' => 'SAST','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Stockholm','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Zurich','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Asia/Damascus','short_code' => 'EET','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Taipei','short_code' => 'CST','gmt_offset' => 'UTC +08:00'],
            ['zone_name' => 'Asia/Dushanbe','short_code' => 'TJT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Africa/Dar_es_Salaam','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Bangkok','short_code' => 'ICT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'Asia/Dili','short_code' => 'TLT','gmt_offset' => 'UTC +09:00'],
            ['zone_name' => 'Africa/Lome','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'Pacific/Fakaofo','short_code' => 'TKT','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'Pacific/Tongatapu','short_code' => 'TOT','gmt_offset' => 'UTC +13:00'],
            ['zone_name' => 'America/Port_of_Spain','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Africa/Tunis','short_code' => 'CET','gmt_offset' => 'UTC +01:00'],
            ['zone_name' => 'Europe/Istanbul','short_code' => 'TRT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Ashgabat','short_code' => 'TMT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'America/Grand_Turk','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'Pacific/Funafuti','short_code' => 'TVT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Africa/Kampala','short_code' => 'EAT','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Europe/Kyiv','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Simferopol','short_code' => 'MSK','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Asia/Dubai','short_code' => 'GST','gmt_offset' => 'UTC +04:00'],
            ['zone_name' => 'Europe/London','short_code' => 'GMT','gmt_offset' => 'UTC'],
            ['zone_name' => 'America/Adak','short_code' => 'HST','gmt_offset' => 'UTC -10:00'],
            ['zone_name' => 'America/Anchorage','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'America/Boise','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Chicago','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Denver','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Detroit','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Indianapolis','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Knox','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Indiana/Marengo','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Petersburg','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Tell_City','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Indiana/Vevay','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Vincennes','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Indiana/Winamac','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Juneau	','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'America/Kentucky/Louisville','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Kentucky/Monticello','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Los_Angeles','short_code' => 'PST','gmt_offset' => 'UTC -08:00'],
            ['zone_name' => 'America/Menominee','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Metlakatla','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'America/New_York','short_code' => 'EST','gmt_offset' => 'UTC -05:00'],
            ['zone_name' => 'America/Nome','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'America/North_Dakota/Beulah','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/North_Dakota/Center','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/North_Dakota/New_Salem','short_code' => 'CST','gmt_offset' => 'UTC -06:00'],
            ['zone_name' => 'America/Phoenix','short_code' => 'MST','gmt_offset' => 'UTC -07:00'],
            ['zone_name' => 'America/Sitka','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'America/Yakutat','short_code' => 'AKST','gmt_offset' => 'UTC -09:00'],
            ['zone_name' => 'Pacific/Honolulu','short_code' => 'HST','gmt_offset' => 'UTC -10:00'],
            ['zone_name' => 'Pacific/Midway','short_code' => 'SST','gmt_offset' => 'UTC -11:00'],
            ['zone_name' => 'Pacific/Wake','short_code' => 'WAKT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'America/Montevideo','short_code' => 'UYT','gmt_offset' => 'UTC -03:00'],
            ['zone_name' => 'Asia/Samarkand','short_code' => 'UZT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Asia/Tashkent','short_code' => 'UZT','gmt_offset' => 'UTC +05:00'],
            ['zone_name' => 'Pacific/Efate','short_code' => 'VUT','gmt_offset' => 'UTC +11:00'],
            ['zone_name' => 'America/Caracas','short_code' => 'VET','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Asia/Ho_Chi_Minh','short_code' => 'IDT','gmt_offset' => 'UTC +07:00'],
            ['zone_name' => 'America/Tortola','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'America/St_Thomas','short_code' => 'AST','gmt_offset' => 'UTC -04:00'],
            ['zone_name' => 'Pacific/Wallis','short_code' => 'WFT','gmt_offset' => 'UTC +12:00'],
            ['zone_name' => 'Asia/Aden','short_code' => 'AST','gmt_offset' => 'UTC +03:00'],
            ['zone_name' => 'Africa/Lusaka','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Africa/Harare','short_code' => 'CAT','gmt_offset' => 'UTC +02:00'],
            ['zone_name' => 'Europe/Mariehamn','short_code' => 'EET','gmt_offset' => 'UTC +02:00'],
        ];

        foreach($data as $datum){
            $timezone = Timezone::where('zone_name', $datum['zone_name'])->first();

            if (!$timezone) {
                $timezone = new Timezone();
                $timezone->uid = Str::orderedUuid();
            }   

            $timezone->zone_name = $datum['zone_name'];
            $timezone->short_code = $datum['short_code'];
            $timezone->gmt_offset = $datum['gmt_offset'];
            $timezone->save();
        }
       
    }
}
