name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo "${{ github.ref_name }}")"
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Select DROPLET_IP based on branch
          branch=${{ steps.branch_name.outputs.branch }}
          ssh-keyscan -H ${{ secrets.DROPLET_IP_${branch^^} }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          # Determine the branch name from the event payload
          branch=${{ steps.branch_name.outputs.branch }}

          # SSH into the Droplet and execute deployment script with branch parameter
          ssh -i ~/.ssh/id_rsa ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP_${branch^^} }} "bash -s" < deploy.sh $branch
